# Generated by Django 5.1.7 on 2025-04-30 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_service', '0003_alter_comment_likes_count_alter_post_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='social_service.post', verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='liked_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата лайка'),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='liked_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата лайка'),
        ),
    ]
