# Generated by Django 5.1.7 on 2025-05-11 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Поисковый идентификатор')),
            ],
            options={
                'verbose_name': 'Категория задания',
                'verbose_name_plural': 'Категории задания',
            },
        ),
        migrations.CreateModel(
            name='TaskRewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('additional_reward_description', models.TextField(blank=True, help_text='Описание дополнительной награды', verbose_name='Описание дополнительной награды')),
            ],
            options={
                'verbose_name': 'Награда задания',
                'verbose_name_plural': 'Награды задания',
            },
        ),
        migrations.CreateModel(
            name='UsersTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_user_name', models.CharField(blank=True, default='Без имени', max_length=150, verbose_name='Имя целевого пользователя')),
                ('status', models.CharField(choices=[('confirmed', 'подтверждено'), ('canceled', 'отменено'), ('started', 'начато'), ('completed', 'завершено')], default='started', max_length=21, verbose_name='Статус')),
                ('invitation_token', models.CharField(blank=True, help_text='Идентификатор анонимного пользователя', max_length=100, null=True, unique=True, verbose_name='Токен приглашения')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка целевого пользователя')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения')),
            ],
            options={
                'verbose_name': 'Задание пользователя',
                'verbose_name_plural': 'Задания пользователей',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Поисковый идентификатор')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('difficulty', models.CharField(choices=[('easy', 'легко'), ('medium', 'средняя сложность'), ('hard', 'сложно')], default='easy', max_length=20, verbose_name='Сложность')),
                ('short_description', models.TextField(help_text='Краткое описание задания')),
                ('hint', models.TextField(blank=True, help_text='Подсказка к заданию')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(related_name='tasks', to='challenge_engine.categorytasks', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['-created_at'],
            },
        ),
    ]
