# Generated by Django 5.1.7 on 2025-04-26 20:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Поисковый идентификатор')),
            ],
            options={
                'verbose_name': 'Категория задания',
                'verbose_name_plural': 'Категории задания',
            },
        ),
        migrations.CreateModel(
            name='TaskRewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Награда задания',
                'verbose_name_plural': 'Награды задания',
            },
        ),
        migrations.CreateModel(
            name='UsersTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_user_name', models.CharField(blank=True, default='Без имени', max_length=150, verbose_name='Имя целевого пользователя')),
                ('status', models.CharField(choices=[('completed', 'завершено'), ('started', 'начато'), ('confirmed', 'подтверждено')], default='started', max_length=10, verbose_name='Статус')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка целевого пользователя')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения')),
            ],
            options={
                'verbose_name': 'Задание пользователя',
                'verbose_name_plural': 'Задания пользователей',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Поисковый идентификатор')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('difficult', models.IntegerField(choices=[(1, 'легко'), (2, 'средняя сложность'), (3, 'сложно')], verbose_name='Сложность')),
                ('category', models.ManyToManyField(related_name='tasks', to='challenge_engine.categorytasks')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
    ]
