# Generated by Django 5.1.7 on 2025-05-11 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenge_engine', '0001_initial'),
        ('user_service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrewards',
            name='additional_reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_task_rewards', to='user_service.skill', verbose_name='Дополнительная награда'),
        ),
        migrations.AddField(
            model_name='taskrewards',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_rewards', to='user_service.skill', verbose_name='Награда'),
        ),
        migrations.AddField(
            model_name='taskrewards',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_rewards', to='challenge_engine.task', verbose_name='Задание'),
        ),
        migrations.AddField(
            model_name='task',
            name='rewards',
            field=models.ManyToManyField(related_name='tasks', through='challenge_engine.TaskRewards', to='user_service.skill', verbose_name='Награды'),
        ),
        migrations.AddField(
            model_name='userstasks',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор'),
        ),
        migrations.AddField(
            model_name='userstasks',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Целевой пользователь'),
        ),
        migrations.AddField(
            model_name='userstasks',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to='challenge_engine.task', verbose_name='Задание'),
        ),
        migrations.AlterUniqueTogether(
            name='taskrewards',
            unique_together={('task', 'reward')},
        ),
    ]
