# Generated by Django 5.1.7 on 2025-04-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_engine', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstasks',
            name='status',
            field=models.CharField(choices=[('completed', 'завершено'), ('confirmed', 'подтверждено'), ('started', 'начато')], default='started', max_length=10, verbose_name='Статус'),
        ),
    ]
