# Generated by Django 5.1.7 on 2025-05-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_engine', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskrewards',
            name='additional_reward',
        ),
        migrations.AddField(
            model_name='taskrewards',
            name='is_additional',
            field=models.BooleanField(default=False, help_text='Является ли эта награда дополнительной', verbose_name='Дополнительная награда'),
        ),
        migrations.AlterField(
            model_name='userstasks',
            name='status',
            field=models.CharField(choices=[('started', 'начато'), ('canceled', 'отменено'), ('confirmed', 'подтверждено'), ('completed', 'завершено')], default='started', max_length=21, verbose_name='Статус'),
        ),
    ]
