# Generated by Django 5.1.7 on 2025-05-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_engine', '0003_remove_taskrewards_additional_reward_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstasks',
            name='invitation_token',
        ),
        migrations.AddField(
            model_name='userstasks',
            name='confirmation_id',
            field=models.CharField(blank=True, help_text='ID для подтверждения задания', max_length=100, null=True, unique=True, verbose_name='ID подтверждения'),
        ),
        migrations.AlterField(
            model_name='userstasks',
            name='status',
            field=models.CharField(choices=[('started', 'начато'), ('confirmed', 'подтверждено'), ('canceled', 'отменено'), ('completed', 'завершено')], default='started', max_length=21, verbose_name='Статус'),
        ),
    ]
