# Generated by Django 5.1.7 on 2025-04-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_engine', '0003_alter_userstasks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstasks',
            name='status',
            field=models.CharField(choices=[('started', 'начато'), ('confirmed', 'подтверждено'), ('completed', 'завершено')], default='started', max_length=10, verbose_name='Статус'),
        ),
    ]
