# Generated by Django 5.1.7 on 2025-04-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_engine', '0004_alter_userstasks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstasks',
            name='status',
            field=models.CharField(choices=[('confirmed', 'подтверждено'), ('started', 'начато'), ('completed', 'завершено')], default='started', max_length=10, verbose_name='Статус'),
        ),
    ]
