# Generated by Django 5.1.7 on 2025-05-10 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_engine', '0005_alter_userstasks_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstasks',
            options={'ordering': ['-started_at'], 'verbose_name': 'Задание пользователя', 'verbose_name_plural': 'Задания пользователей'},
        ),
        migrations.AddField(
            model_name='userstasks',
            name='invitation_token',
            field=models.CharField(blank=True, help_text='Идентификатор анонимного пользователя', max_length=100, null=True, unique=True, verbose_name='Токен приглашения'),
        ),
        migrations.AlterField(
            model_name='userstasks',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор'),
        ),
        migrations.AlterField(
            model_name='userstasks',
            name='status',
            field=models.CharField(choices=[('canceled', 'отменено'), ('confirmed', 'подтверждено'), ('started', 'начато'), ('completed', 'завершено')], default='started', max_length=21, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='userstasks',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Целевой пользователь'),
        ),
        migrations.AlterField(
            model_name='userstasks',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to='challenge_engine.task', verbose_name='Задание'),
        ),
    ]
